version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: auto_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/migrations:/docker-entrypoint-initdb.d/
    ports:
      - "192.168.2.10:5434:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - auto-service-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "192.168.2.10:5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/auto_service_db?sslmode=disable
      - JWT_SECRET=auto-service-super-secret-jwt-key-2024
      - FRONTEND_URL=http://192.168.2.10:3003
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - auto-service-network

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "192.168.2.10:3003:80"
    environment:
      - VITE_API_URL=http://192.168.2.10:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - auto-service-network

volumes:
  postgres_data:

networks:
  auto-service-network:
    driver: bridge
