version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: auto_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/001_initial_schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  auto-service-app:
    build: .
    ports:
      - "3000:80"
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/auto_service_db
      - JWT_SECRET=auto-service-super-secret-jwt-key-2024
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    container_name: auto-service-management

volumes:
  postgres_data:

networks:
  default:
    name: auto-service-network